# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/moon/moon/moon_experiment/ing5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/moon/moon/moon_experiment/ing5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moon/moon/moon_experiment/ing5/CMakeFiles /home/moon/moon/moon_experiment/ing5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moon/moon/moon_experiment/ing5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ing5

# Build rule for target.
ing5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ing5
.PHONY : ing5

# fast build rule for target.
ing5/fast:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/build
.PHONY : ing5/fast

SFM.o: SFM.cpp.o

.PHONY : SFM.o

# target to build an object file
SFM.cpp.o:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/SFM.cpp.o
.PHONY : SFM.cpp.o

SFM.i: SFM.cpp.i

.PHONY : SFM.i

# target to preprocess a source file
SFM.cpp.i:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/SFM.cpp.i
.PHONY : SFM.cpp.i

SFM.s: SFM.cpp.s

.PHONY : SFM.s

# target to generate assembly for a file
SFM.cpp.s:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/SFM.cpp.s
.PHONY : SFM.cpp.s

bundle.o: bundle.cpp.o

.PHONY : bundle.o

# target to build an object file
bundle.cpp.o:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/bundle.cpp.o
.PHONY : bundle.cpp.o

bundle.i: bundle.cpp.i

.PHONY : bundle.i

# target to preprocess a source file
bundle.cpp.i:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/bundle.cpp.i
.PHONY : bundle.cpp.i

bundle.s: bundle.cpp.s

.PHONY : bundle.s

# target to generate assembly for a file
bundle.cpp.s:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/bundle.cpp.s
.PHONY : bundle.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/main.cpp.s
.PHONY : main.cpp.s

my_utils.o: my_utils.cpp.o

.PHONY : my_utils.o

# target to build an object file
my_utils.cpp.o:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/my_utils.cpp.o
.PHONY : my_utils.cpp.o

my_utils.i: my_utils.cpp.i

.PHONY : my_utils.i

# target to preprocess a source file
my_utils.cpp.i:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/my_utils.cpp.i
.PHONY : my_utils.cpp.i

my_utils.s: my_utils.cpp.s

.PHONY : my_utils.s

# target to generate assembly for a file
my_utils.cpp.s:
	$(MAKE) -f CMakeFiles/ing5.dir/build.make CMakeFiles/ing5.dir/my_utils.cpp.s
.PHONY : my_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ing5"
	@echo "... edit_cache"
	@echo "... SFM.o"
	@echo "... SFM.i"
	@echo "... SFM.s"
	@echo "... bundle.o"
	@echo "... bundle.i"
	@echo "... bundle.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... my_utils.o"
	@echo "... my_utils.i"
	@echo "... my_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

